name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    env:
      _Solution: DPackRx.sln
      _Config: Debug

    steps:
    - uses: actions/checkout@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Restore Nuget Packages
      run: nuget restore $_Solution

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v1

    - name: Build Solution
      run: msbuild $_Solution -verbosity:normal -p:Configuration=$_Config /p:Platform="Any CPU" -p:DeployExtension=false -p:AzureVsixVersion=true
