name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Restores Packages
      run: nuget restore DPackRx.sln

    - name: Build Solution
      run: msbuild DPackRx.sln -verbosity:minimal /p:DeployExtension=false


